### ISSUE TITLE
Wrong encoding used

### ISSUE THREAD

**Issue by patrikr** [stephenjtong/rss#11]
Hi,

I created a feed for this JSON:

https://esco.elisa.fi/rest/esco/bulletin/list?tags=corporate.elisa.fi:customer,elisa.fi:customer&jsonp=jsonpBulletinListing

(https://rsseverything.com/feed/a68c0788-a938-4b61-be2f-cc4c11a3f49f.xml)

However, the wrong encoding is used, all the ä and ö letters turn into Chinese characters. The encoding is set to UTF-8 in the headers (Content-Type: application/json;charset=UTF-8) and the data looks correctly encoded, so this seems to be a bug in RssEverything.

**Comment by stephenjtong** [comment]
checking

**Comment by stephenjtong** [comment]
Done
