### ISSUE TITLE
Health check for feeds

### ISSUE THREAD

**Issue by stephenjtong** [stephenjtong/rss#4]

**Comment by Perkolator** [comment]
I suggested these in the discussion topic:

1) If the source URL doesn't work (not reachable/404, whatever that prevents from reading the source page code) that would definitely be an error. That's how Inoreader works too (without seeing their code).

2) If the "Search Pattern" doesn't return anything, then it would be an error, right? That is a "required" data to create the feed in the first place. EDIT: Clarification: I mean that if any of of the "{%}"-parameters in the search pattern the user has made return as empty = error.

3) If the feed has not seen any new items past X days (user selectable? e.g. with some high traffic feeds, notification after 1 week of no updates would make sense, with not that often updated feeds, notification after e.g. 1/2/3 months of no updates would suit better). Inoreader has also this kind of feature in different parts of their service, e.g. their "Statistics" or "Inactive feeds" gadgets that could be added to the "Dashboard". This would not be an error but a warning.
