### ISSUE TITLE
RSSEverything can't locate the location I need correctly.

### ISSUE THREAD

**Issue by Lao-Tz** [stephenjtong/rss#5]
The website I tested was [Single cell sequencing algorithm](https://pubmed.ncbi.nlm.nih.gov/?term=%28single+cell+RNA-seq%5BTitle%2FAbstract%5D+OR+scRNA-seq%5BTitle%2FAbstract%5D+OR+RNA+sequencing%5BTitle%2FAbstract%5D+OR+single+cell+sequencing%5BTitle%2FAbstract%5D+OR+single+cell+transcriptomics%5BTitle%2FAbstract%5D%29+AND+%28algorithm%5BTitle%2FAbstract%5D+OR+computational+method%5BTitle%2FAbstract%5D+OR+analysis+tool%5BTitle%2FAbstract%5D+OR+pipeline%5BTitle%2FAbstract%5D+OR+software%5BTitle%2FAbstract%5D+OR+model%5BTitle%2FAbstract%5D+OR+framework%5BTitle%2FAbstract%5D%29+AND+%28Nature+Methods%5BJournal%5D+OR+Genome+Biology%5BJournal%5D+OR+Cell%5BJournal%5D+OR+Nature+Biotechnology%5BJournal%5D+OR+Genome+Research%5BJournal%5D+OR+Nucleic+Acids+Research%5BJournal%5D%29+AND+%28alignment%5BTitle%2FAbstract%5D+OR+clustering%5BTitle%2FAbstract%5D+OR+dimensionality+reduction%5BTitle%2FAbstract%5D+OR+visualization%5BTitle%2FAbstract%5D+OR+differential+expression%5BTitle%2FAbstract%5D+OR+trajectory+inference%5BTitle%2FAbstract%5D%29+AND+%28%222021%2F01%2F01%22%5BPDAT%5D+%3A+%223000%2F12%2F31%22%5BPDAT%5D%29)
I copied the internal selection of "Page source code" to UE for detailed analysis.
When I write `<div class="docsum-content">{%}</div>`
What is located is the content that needs to be extracted within the normal 2000 lines：
![image](https://github.com/stephenjtong/rss/assets/93063057/71811a59-7674-4332-89cf-4954969574d2)

I want to extract`<a href="{%}">`
When I write `<div class="docsum-content">{*}<a href="{%}">{*}</a>{*}</div>`
I ran to more than 4,000 lines.
![image](https://github.com/stephenjtong/rss/assets/93063057/700feb80-e71a-4028-ab5b-31f84b5f3df2)

I am very confused about this. The above may not be the problem of RSSEverything. I hope I can get your help!

**Comment by stephenjtong** [comment]
`<div class="docsum-content">{*}<a{*}href="{%}"`

<img width="585" alt="image" src="https://github.com/stephenjtong/rss/assets/541568/93b8c7b4-f34e-43a2-8eb3-24a1996b58f2">

Please examine the source code carefully. Generally speaking, writing rules is not an issue.

**Comment by Lao-Tz** [comment]
I am new to using GPT-4 and I found your previous response very helpful. Thank you for your enthusiastic reply!

I have a follow-up question: Does RSSEverything support regular expression filtering? I am trying to extract titles from RSS feeds, like this `<div class="docsum-content">{*}<a{*}href="{%}"{*}<b>{%}.{*}>`.but I noticed that many titles have bold formatting represented by <b> tags. For example, the content returned is:

```
Item 1
{%1} = https://pubmed.ncbi.nlm.nih.gov/34019793/
{%2} = Single</b>-<b>cell</b> protein activity <b>analysis</b> identifies recurrence-associated renal tumor macrophages

Item 2
{%1} = https://pubmed.ncbi.nlm.nih.gov/33932341/
{%2} = single</b>-embryo, <b>single</b>-<b>cell</b> time-resolved <b>model</b> for mouse gastrulation
...
```

GPT-4 suggested modifying `<div class="docsum-content">{*}<a{*}href="{%}"{*}<b>{%}.{*}>|replace('<b>|</b>','')`, but it doesn't work. Could you please provide some guidance?

Thank you again for creating such a useful tool for working with RSS feeds.

**Comment by Lao-Tz** [comment]
I'm happy to report that I have finished creating the feed and it is displaying properly in Feedbro. I couldn't have done it without your guidance, so I really appreciate your assistance.

Thanks again!

**Comment by stephenjtong** [comment]
Yes, having <b> in the title shouldn't affect anything.
