### ISSUE TITLE
How to deal with a webpage that has encoding issues

### ISSUE THREAD

**Issue by enterlet** [stephenjtong/rss#8]
For example, this webpage (https://www.ahzll.top/HELP/update.html) has encoding issues, so the page source code is garbled when creating a new feed.

**Comment by stephenjtong** [comment]
There's no meta tag for charset in this page. I will add an option for
encoding.

**Comment by stephenjtong** [comment]
Fixed, please check.

<img width="992" alt="image" src="https://github.com/stephenjtong/rss/assets/541568/456e5b61-82a8-4129-b9b4-e92f118867cc">

**Comment by enterlet** [comment]
Ok. Thank you.
